### ISSUE TITLE
Global Memory to GPU Bandwidth

### ISSUE THREAD

**Issue by harryshu1997** [microsoft/ArchProbe#11]
Could you please indicate where can I find the data about bandwidth between global memory and GPU from the ArchProbeReport.json? I couldn't find any data about it, but in the example graph you have the value like 28 GB/s. Thanks!

**Comment by PENGUINLIONG** [comment]
[This one](https://github.com/microsoft/ArchProbe/blob/main/examples/adreno640/Google_Pixel_4/BufferBandwidth.csv) shall be it. The algorithm is updated once after the paper for more accurate result so there might be some discrepancy in figures. Sorry about that tho.

The theoretical bandwidth should be something like 31 GB/s AFAIR

**Comment by PENGUINLIONG** [comment]
I'm gonna close this issue since the link should suffice. But do let me know and please feel free to reopen it if you have further concerns.
