### ISSUE TITLE
Logic clarification for image cache line size calculation

### ISSUE THREAD

**Issue by Esteb37** [microsoft/ArchProbe#12]
Hello,

I am interested in knowing if you could provide further clarification on the logic behind the cache line size calculation for images, utilizing the ratio between concurrencies, as seen [here](https://github.com/microsoft/ArchProbe/blob/53aff57fb49ffd7a5df45359d4b4867c06f4ee8b/apps/archprobe/app.cpp#L570C5-L582C1).

```
cacheline_size = PX_SIZE * std::max(concur_nthread_x, concur_nthread_y) /
        std::min(concur_nthread_x, concur_nthread_y);


cacheline_dim = concur_nthread_x >= concur_nthread_y ? "X" : "Y";
```

My questions are: 

- What is the reasoning behind this ratio? 
- What do you refer to when speaking of a "cache line dimension"? 
- How would you extend it to a third dimension?

Thank you and great work developing this tool :)

**Comment by PENGUINLIONG** [comment]
In the paper we discussed 2D textures. 2D textures can layout the pixels either by rows or columns so the ratio is basically the number of texels in a cacheline divided by 1.

The above reasoning certainly generalizes to 3D textures but they are seldomly used in mobile applications. Drivers usually don't layout in the third dim so we don't spend much time on that.

**Comment by PENGUINLIONG** [comment]
I'm closing this for non-activity. Feel free to reopen if you have further questions
