### ISSUE TITLE
Does this contains the code to reproduce or generate the figures or data of the document?

### ISSUE THREAD

**Issue by Smeegol** [microsoft/ArchProbe#3]
Does this contains the code to reproduce or generate the figures or data of the document ["Romou: Rapidly Generate High-Performance Tensor Kernels for Mobile GPUs"](https://www.microsoft.com/en-us/research/publication/romou-rapidly-generate-high-performance-tensor-kernels-for-mobile-gpus/)?

**Comment by PENGUINLIONG** [comment]
You can find raw data in the generated `.csv` files. For example here: https://github.com/microsoft/ArchProbe/tree/main/examples/adreno640/Google_Pixel_4

I usually plot the outputs in Excel in some early days so it doesn't take any fancy plotting technique to generate the figures in the paper. The raw outputs are expressive enough.

**Comment by Smeegol** [comment]
Yeah, I also generate outputs too, thank you.
