### ISSUE TITLE
Is rooting required?

### ISSUE THREAD

**Issue by aseok** [microsoft/ArchProbe#9]
Facing permission denied copying to /data/local/tmp.

**Comment by PENGUINLIONG** [comment]
Hmm. It shouldn't. One of our test device (the Vivo one) doesn't support rooting but we still carried out our experiments on it with no pain. Maybe your vendor has been too aggresive or maybe you forgot to turn on the developer mode?

**Comment by aseok** [comment]
Device is poco f3, testing in developer mode. Is there already any log of snapdragon 870 GPU?

**Comment by PENGUINLIONG** [comment]
That's funny. We don't have it yet. Though, Qualcomm's GPUs don't change a lot so maybe you can check out the Snapdragon 855 results as reference.

**Comment by PENGUINLIONG** [comment]
If there's no other question I'm gonna close this. Feel free to open another if you have further questions. 😉
